apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kubeapp-github-deployer
  labels:
    kubecore.io/type: kubeapp
spec:
  compositeTypeRef:
    apiVersion: kubecore.io/v1alpha1
    kind: XKubeApp
  mode: Pipeline
  pipeline:
  - step: commit-app-files
    functionRef:
      name: function-github-file-manager
    input:
      apiVersion: github.fn.kubecore.io/v1beta1
      kind: Input
      spec:
        githubToken: "{{ .observed.composite.resource.spec.githubToken }}"
        files:
        - repository: "{{ .observed.composite.resource.spec.repository }}"
          branch: "main"
          path: "kubeapps/{{ .observed.composite.resource.metadata.name }}/base/resources.yaml"
          content: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: {{ .observed.composite.resource.metadata.name }}
              labels:
                app: {{ .observed.composite.resource.metadata.name }}
            spec:
              replicas: {{ .observed.composite.resource.spec.replicas | default 1 }}
              selector:
                matchLabels:
                  app: {{ .observed.composite.resource.metadata.name }}
              template:
                metadata:
                  labels:
                    app: {{ .observed.composite.resource.metadata.name }}
                spec:
                  containers:
                  - name: {{ .observed.composite.resource.metadata.name }}
                    image: {{ .observed.composite.resource.spec.image }}
                    ports:
                    - containerPort: {{ .observed.composite.resource.spec.port | default 8080 }}
            ---
            apiVersion: v1
            kind: Service
            metadata:
              name: {{ .observed.composite.resource.metadata.name }}-svc
              labels:
                app: {{ .observed.composite.resource.metadata.name }}
            spec:
              selector:
                app: {{ .observed.composite.resource.metadata.name }}
              ports:
              - port: 80
                targetPort: {{ .observed.composite.resource.spec.port | default 8080 }}
          commitMessage: "Deploy {{ .observed.composite.resource.metadata.name }} - generated by Crossplane"

        - repository: "{{ .observed.composite.resource.spec.repository }}"
          branch: "main"
          path: "kubeapps/{{ .observed.composite.resource.metadata.name }}/base/kustomization.yaml"
          content: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
            - resources.yaml
            commonLabels:
              kubeapp: {{ .observed.composite.resource.metadata.name }}
              kubecore.io/managed-by: crossplane
          commitMessage: "Add kustomization for {{ .observed.composite.resource.metadata.name }}"
