apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kubeapp-github-deployer
  labels:
    kubecore.io/type: kubeapp
spec:
  compositeTypeRef:
    apiVersion: kubecore.io/v1alpha1
    kind: XKubeApp
  mode: Pipeline
  pipeline:
  - step: commit-app-files
    functionRef:
      name: function-github-file-manager
    input:
      apiVersion: github.fn.kubecore.io/v1beta1
      kind: Input
      spec:
        # Option 1: Personal Access Token Authentication
        # githubToken: "{{ .observed.composite.resource.spec.githubToken }}"
        
        # Option 2: GitHub App Authentication (Recommended for production)
        githubApp:
          appId: "{{ .observed.composite.resource.spec.githubApp.appId }}"
          installationId: "{{ .observed.composite.resource.spec.githubApp.installationId }}"
          privateKey: "{{ .observed.composite.resource.spec.githubApp.privateKey }}"
        
        files:
        - repository: "{{ .observed.composite.resource.spec.repository }}"
          branch: "main"
          path: "kubeapps/{{ .observed.composite.resource.metadata.name }}/base/resources.yaml"
          content: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: {{ .observed.composite.resource.metadata.name }}
              labels:
                app: {{ .observed.composite.resource.metadata.name }}
                kubecore.io/managed-by: crossplane
            spec:
              replicas: {{ .observed.composite.resource.spec.replicas | default 1 }}
              selector:
                matchLabels:
                  app: {{ .observed.composite.resource.metadata.name }}
              template:
                metadata:
                  labels:
                    app: {{ .observed.composite.resource.metadata.name }}
                spec:
                  containers:
                  - name: {{ .observed.composite.resource.metadata.name }}
                    image: {{ .observed.composite.resource.spec.image }}
                    ports:
                    - containerPort: {{ .observed.composite.resource.spec.port | default 8080 }}
                    env:
                    - name: PORT
                      value: "{{ .observed.composite.resource.spec.port | default 8080 }}"
            ---
            apiVersion: v1
            kind: Service
            metadata:
              name: {{ .observed.composite.resource.metadata.name }}-svc
              labels:
                app: {{ .observed.composite.resource.metadata.name }}
                kubecore.io/managed-by: crossplane
            spec:
              selector:
                app: {{ .observed.composite.resource.metadata.name }}
              ports:
              - port: 80
                targetPort: {{ .observed.composite.resource.spec.port | default 8080 }}
              type: ClusterIP
          commitMessage: "Deploy {{ .observed.composite.resource.metadata.name }} via Crossplane GitHub File Manager"
          
        - repository: "{{ .observed.composite.resource.spec.repository }}"
          branch: "main"
          path: "kubeapps/{{ .observed.composite.resource.metadata.name }}/base/kustomization.yaml"
          content: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
            - resources.yaml
            commonLabels:
              kubeapp: {{ .observed.composite.resource.metadata.name }}
              kubecore.io/managed-by: crossplane
            namespace: {{ .observed.composite.resource.spec.namespace | default "default" }}
          commitMessage: "Add kustomization for {{ .observed.composite.resource.metadata.name }}"
          
        # Optional: Add environment-specific overlays
        {{ if .observed.composite.resource.spec.environments }}
        {{ range $env := .observed.composite.resource.spec.environments }}
        - repository: "{{ $.observed.composite.resource.spec.repository }}"
          branch: "main"
          path: "kubeapps/{{ $.observed.composite.resource.metadata.name }}/overlays/{{ $env }}/kustomization.yaml"
          content: |
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
            - ../../base
            namePrefix: "{{ $env }}-"
            namespace: "{{ $env }}"
          commitMessage: "Add {{ $env }} overlay for {{ $.observed.composite.resource.metadata.name }}"
        {{ end }}
        {{ end }}
