apiVersion: kubecore.io/v1alpha1
kind: XKubeApp
metadata:
  name: example-rest-api
spec:
  # GitHub settings
  githubToken: "ghp_xxxxxxxxxxxxxxxxxxxx" # Real token would be from secret ref
  repository: "novelcore/xdp-idp"

  # Application settings
  image: "nginx:latest"
  port: 8080
  replicas: 2
