---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inputs.github.fn.kubecore.io
spec:
  group: github.fn.kubecore.io
  names:
    categories:
    - crossplane
    kind: Input
    listKind: InputList
    plural: inputs
    singular: input
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Input for GitHub File Manager function to commit files to GitHub repositories.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Specification for GitHub file management operation.
            properties:
              githubToken:
                description: GitHub personal access token for authentication.
                type: string
              files:
                description: List of files to commit to GitHub repositories.
                type: array
                items:
                  type: object
                  properties:
                    repository:
                      description: GitHub repository in format "owner/repo".
                      type: string
                    branch:
                      description: Target branch for the commit (default is main).
                      type: string
                      default: main
                    path:
                      description: File path within the repository.
                      type: string
                    content:
                      description: File content to commit.
                      type: string
                    commitMessage:
                      description: Commit message for this file.
                      type: string
                  required:
                  - repository
                  - path
                  - content
                  - commitMessage
            required:
            - githubToken
            - files
        type: object
    served: true
    storage: true
